---
abstract: 'JavaScript Modules on CPAN'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: JS
name: JS
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Filter::Util::Call: 0
  perl: 5.8.0
resources:
  homepage: https://github.com/ingydotnet/js-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/js-pm.git
    web: https://github.com/ingydotnet/js-pm/tree
version: 0.18
